const pasteleriaRecetas = [
  {
    id: "TM",
    nombre: "Torta de Manzana",
    dificultad: 5,
    puntuacion: 7,
    tiempo: "30 min",
    nuevo: true,
    sinAzucar: false,
    img: require("./01.jpg"),
  },
  {
    id: "HK",
    nombre: "Hot Cake",
    dificultad: 2,
    puntuacion: 7,
    tiempo: "15 min",
    nuevo: false,
    sinAzucar: false,
    img: require("./02.jpg"),
  },
  {
    id: "TF",
    nombre: "Tarta de Frutilla",
    dificultad: 6,
    puntuacion: 8,
    tiempo: "1 h",
    nuevo: true,
    sinAzucar: false,
    img: require("./03.jpg"),
  },
  {
    id: "CF",
    nombre: "Canasta Frutal",
    dificultad: 2,
    puntuacion: 6,
    tiempo: "50 min",
    nuevo: false,
    sinAzucar: true,
    img: require("./04.jpg"),
  },
  {
    id: "TC",
    nombre: "Tarta de Calzabaza",
    dificultad: 5,
    puntuacion: 9,
    tiempo: "1 h",
    nuevo: true,
    sinAzucar: true,
    img: require("./05.jpg"),
  },
  {
    id: "CC",
    nombre: "Cheesecake",
    dificultad: 5,
    puntuacion: 10,
    tiempo: "50 min h",
    nuevo: false,
    sinAzucar: false,
    img: require("./06.jpg"),
  },
  {
    id: "CFR",
    nombre: "Canasta F.rojos",
    dificultad: 5,
    puntuacion: 9,
    tiempo: "1,25 h",
    nuevo: false,
    sinAzucar: false,
    img: require("./07.jpg"),
  },
  {
    id: "TI",
    nombre: "Torta Invertida",
    dificultad: 6,
    puntuacion: 5,
    tiempo: "1,15 h",
    nuevo: false,
    sinAzucar: false,
    img: require("./08.jpg"),
  },
  {
    id: "CB",
    nombre: "Creme Brulee",
    dificultad: 7,
    puntuacion: 10,
    tiempo: "1,30 h",
    nuevo: false,
    sinAzucar: false,
    img: require("./09.jpg"),
  },
];

export default pasteleriaRecetas;
